version = 0.1

[default.deploy.parameters]
stack_name = "smart-fridge-dev-gaga"
resolve_s3 = true
s3_prefix = "smart-fridge-dev-gaga"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"dev\" DeviceId=\"smart-fridge-001\" MockMode=\"false\" SesFromEmail=\"gaga555lala@gmail.com\" LambdaExecutionRoleArn=\"arn:aws:iam::491919374787:role/SmartFridgeLambdaExecutionRole\" LambdaExecutionRoleName=\"SmartFridgeLambdaExecutionRole\""
image_repositories = []

[default.global.parameters]
region = "ap-northeast-1"
